package com.mycompany.elchou;

import java.awt.Image;

/*
 * 
 * @author UNFV
 */
public class Ingreso extends javax.swing.JPanel {
    
    int intentos = 0;
    
    /**
     * Creates new form Ingreso
     */
    public Ingreso() {
        initComponents();
        setLogoIcon();
    }

    /**
     * Carga y escala el ícono de pollito de forma portable en el JLabel (escalado a 50x50).
     */
    private void setLogoIcon() {
        Image img = null;
        // Intentar cargar desde el classpath
        java.net.URL imgUrl = Ingreso.class.getResource("/com/mycompany/elchou/pollito-icon.png");
        if (imgUrl != null) {
            img = new javax.swing.ImageIcon(imgUrl).getImage();
        } else {
            // Intentar cargar desde la raíz del proyecto
            java.io.File file = new java.io.File("pollito-icon.png");
            if (file.exists()) {
                img = new javax.swing.ImageIcon(file.getAbsolutePath()).getImage();
            } else {
                // Intentar cargar desde la ruta relativa de desarrollo
                file = new java.io.File("src/main/java/com/mycompany/elchou/pollito-icon.png");
                if (file.exists()) {
                    img = new javax.swing.ImageIcon(file.getAbsolutePath()).getImage();
                }
            }
        }
        
        if (img != null) {
            // Escalar a 50x50 para alinearlo de manera armónica al costado del título
            Image scaledImg = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
            lblLogo.setIcon(new javax.swing.ImageIcon(scaledImg));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        lblGeneralMessage = new javax.swing.JLabel();

        setLayout(null);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblLogo);
        lblLogo.setBounds(270, 30, 50, 50);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitle.setText("ComeComelon");
        add(lblTitle);
        lblTitle.setBounds(60, 35, 200, 40);

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuario.setText("Usuario");
        add(lblUsuario);
        lblUsuario.setBounds(40, 100, 300, 20);

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        add(txtUsuario);
        txtUsuario.setBounds(40, 125, 300, 35);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setText("Contraseña");
        add(lblPassword);
        lblPassword.setBounds(40, 175, 300, 20);

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtPassword);
        txtPassword.setBounds(40, 200, 300, 35);

        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIngresar.setText("Iniciar Sesión");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        add(btnIngresar);
        btnIngresar.setBounds(40, 260, 300, 40);

        lblGeneralMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblGeneralMessage);
        lblGeneralMessage.setBounds(40, 315, 300, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String user = txtUsuario.getText().trim();
        String pass = new String(txtPassword.getPassword()).trim();

        if (user.isEmpty() || pass.isEmpty()) {
            lblGeneralMessage.setForeground(new java.awt.Color(220, 38, 38)); // Red-600
            lblGeneralMessage.setText("Completa todos los campos");
        } else if (user.equals("usuario") && pass.equals("12345")) {
            lblGeneralMessage.setForeground(new java.awt.Color(22, 163, 74)); // Green-600
            lblGeneralMessage.setText("Bienvenido");
            
            // Cerrar ventana de login e iniciar el segundo frame (RegistroPlatos)
            javax.swing.JFrame currentFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            if (currentFrame != null) {
                currentFrame.dispose();
            }
            
            javax.swing.SwingUtilities.invokeLater(() -> {
                RegistroPlatos frame2 = new RegistroPlatos();
                frame2.setVisible(true);
            });
        } else if (user.equals("oretarao") && pass.equals("12345")) {
            lblGeneralMessage.setForeground(new java.awt.Color(22, 163, 74)); // Green-600
            lblGeneralMessage.setText("Bienvenido");
            
            // Cerrar ventana de login e iniciar el tercer frame (ListaPlatos como no-admin)
            javax.swing.JFrame currentFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            if (currentFrame != null) {
                currentFrame.dispose();
            }
            
            javax.swing.SwingUtilities.invokeLater(() -> {
                ListaPlatos frame3 = new ListaPlatos(false);
                frame3.setVisible(true);
            });
        } else {
            lblGeneralMessage.setForeground(new java.awt.Color(220, 38, 38)); // Red-600
            lblGeneralMessage.setText("Algo está incorrecto.");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblGeneralMessage;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
